# Generated by Django 5.0.2 on 2024-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='busroute',
            name='bus_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
